export const ANTECEDENTES_OPCIONES = [
  'Diabetes',
  'Hipertensión arterial (Presión alta)',
  'Enfermedades oculares (Miopía, Astigmatismo, etc.)',
  'Enfermedades del corazón',
  'Enfermedades de la piel',
  'Várices',
  'Cáncer',
  'Obesidad',
  'Alcoholismo',
  'Cálculos en riñón',
  'Cálculos en vesícula',
  'Insomnio',
  'Asma',
  'Colesterol',
  'Migraña',
  'Enfermedades mentales',
  'Epilepsia',
  'Enfermedades tiroideas',
  'Anemia',
  'Enfermedades de riñón',
  'Enfermedades de hígado',
  'Enfermedades gástricas',
  'Artritis',
  'Otras',
];

export const HABITOS_OPCIONES = [
  'Alcoholismo',
  'Tabaquismo',
  'Toxicomanías',
];

export const PATOLOGICOS_OPCIONES = [
  'Amigdalitis',
  'Alérgicos',
  'Enf. Venéreas',
  'Traumatismos',
  'Parasitosis',
  'Transfusiones',
  'Cirugías',
  'Cáncer',
  'Enf. Hígado',
  'Enf. Riñones',
  'Corazón',
  'Varicela',
  'Rubéola',
  'Sarampión',
  'Ojos',
  'Gastrointestinal',
  'Respiratorio',
  'Piel',
  'Migraña',
  'Colesterol',
  'Várices',
  'Glucosa',
  'Metabólico',
  'Insomnio',
  'Otros',
];

export const SISTEMAS_OPCIONES = [
  'Síntomas generales',
  'Endocrino',
  'Órganos de los sentidos',
  'Gastrointestinal',
  'Respiratorio',
  'Cardiopulmonar',
  'Genitourinario',
  'Genital femenino',
  'Sexualidad',
  'Dermatológico',
  'Neurológico',
  'Hematológico',
  'Reumatológico',
  'Psiquiátrico',
];

export const INSPECCION_OPCIONES = [
  'Cabeza',
  'Lengua',
  'Cuello',
  'Tórax',
  'Abdomen',
  'Genitales',
  'Extremidades',
  'Pulso',
];
